# Generated by Django 5.2.3 on 2025-11-03 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='creatorprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='always_add_cta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='always_add_emojis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='default_platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('onlyfans', 'OnlyFans'), ('tiktok', 'TikTok'), ('general', 'General')], default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='example_caps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='tone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creatorprofile',
            name='vibe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
