# Generated by Django 5.2.3 on 2025-11-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_creatorprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='niche',
            field=models.CharField(blank=True, help_text='e.g. fitness, OF, beauty, cosplay, foodie, gamer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='target_audience',
            field=models.CharField(blank=True, help_text='e.g. male fans, OF subscribers, IG followers', max_length=100, null=True),
        ),
    ]
