# Generated by Django 5.2.3 on 2025-11-03 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creatorprofile_niche_creatorprofile_target_audience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suggested_caption_starter', models.TextField(blank=True)),
                ('hook_used', models.CharField(blank=True, max_length=255)),
                ('personal_twist', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
