# Generated by Django 5.2.3 on 2025-11-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedidea'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('entertainment', 'Entertainment')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('metric', models.FloatField(default=0)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
    ]
