# Generated by Django 5.2.3 on 2025-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_globaltrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
    ]
