# Generated by Django 5.2.3 on 2025-11-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_creatorprofile_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
                ('day_of_week', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('engagement_rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
