# Generated by Django 5.2.3 on 2025-11-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_platformtiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformtiming',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='platformtiming',
            unique_together={('platform', 'day_of_week', 'hour')},
        ),
    ]
