# Generated by Django 5.2.3 on 2025-11-09 19:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_postperformance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('stripe_price_id', models.CharField(blank=True, max_length=200, null=True)),
                ('ideas_per_month', models.IntegerField(default=50)),
                ('captions_per_month', models.IntegerField(default=30)),
            ],
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='cancelled_at',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='current_period_end',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_sub_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plan'),
        ),
    ]
