# Generated by Django 5.2.3 on 2025-11-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='default_platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('general', 'General'), ('entertainment', 'Entertainment')], default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='globaltrend',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('general', 'General'), ('entertainment', 'Entertainment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('general', 'General'), ('entertainment', 'Entertainment')], max_length=20),
        ),
    ]
