# Generated by Django 5.2.3 on 2025-11-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_creatorprofile_default_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], default='en', help_text='Preferred language for captions and ideas.', max_length=5),
        ),
    ]
