# Generated by Django 5.2.3 on 2025-11-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_creatorprofile_city_creatorprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='content_languages',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='creator_stage',
            field=models.CharField(choices=[('starter', 'Starter'), ('growing', 'Growing'), ('pro', 'Pro')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='marketing_opt_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
