# Generated by Django 5.2.3 on 2025-11-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_creatorprofile_content_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.TextField()),
                ('main_platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM'), ('general', 'General')], default='general', max_length=50)),
                ('vibe', models.CharField(blank=True, max_length=100, null=True)),
                ('tone', models.CharField(blank=True, max_length=100, null=True)),
                ('niche', models.CharField(blank=True, max_length=100, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(default='en', help_text="ISO code like 'en', 'fr', 'es'.", max_length=10)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('always_add_emojis', models.BooleanField(default=True)),
                ('always_add_cta', models.BooleanField(default=False)),
                ('default_platform', models.CharField(choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM'), ('general', 'General')], default='instagram', max_length=50)),
                ('example_caption_hint', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
