# Generated by Django 5.2.3 on 2025-11-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_usecasetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Optional profile picture for the creator.', null=True, upload_to='avatars/'),
        ),
    ]
