# Generated by Django 5.2.3 on 2025-11-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_creatorprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
