# Generated by Django 5.2.3 on 2025-11-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_appreview_supportticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedIdea',
        ),
    ]
