# Generated by Django 5.2.3 on 2025-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_delete_savedidea'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
