# Generated by Django 5.2.3 on 2025-11-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_creatorprofile_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='default_platform',
            field=models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General'), ('entertainment', 'Entertainment')], default='instagram', max_length=50),
        ),
    ]
