# Generated by Django 5.2.3 on 2025-11-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_newsletterblast'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='brand_persona',
            field=models.TextField(blank=True, help_text='JSON blob with AI-generated brand persona (summary, pillars, etc.).', null=True),
        ),
    ]
