# Generated by Django 5.2.3 on 2025-11-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_creatorprofile_brand_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorprofile',
            name='default_platform',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General'), ('entertainment', 'Entertainment')], default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='globaltrend',
            name='platform',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General'), ('entertainment', 'Entertainment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='platform',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General'), ('entertainment', 'Entertainment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usecasetemplate',
            name='default_platform',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General')], default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='usecasetemplate',
            name='main_platform',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('twitch', 'Twitch'), ('onlyfans', 'OnlyFans'), ('mym', 'MYM Fans'), ('snapchat', 'Snapchat'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
