# Generated by Django 5.2.3 on 2025-12-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_creatorprofile_default_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasetemplate',
            name='preferred_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
