# Generated by Django 5.2.3 on 2025-12-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usecasetemplate_preferred_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecasetemplate',
            name='preferred_platforms',
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='preferred_platforms',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
