# Generated by Django 5.2.3 on 2025-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_creatorprofile_notify_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingreminder',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
