# Generated by Django 5.2.3 on 2025-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_notification_options_remove_notification_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='execution_plan',
            field=models.TextField(blank=True),
        ),
    ]
