# Generated by Django 5.2.3 on 2025-12-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_draft_execution_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active_platforms_limit',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='plan',
            name='drafts_limit',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_media_size_mb',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='media_uploads_per_month',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='plan',
            name='posting_reminders_per_month',
            field=models.IntegerField(default=100),
        ),
    ]
