# Generated by Django 5.2.3 on 2025-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_plan_active_platforms_limit_plan_drafts_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='active_platforms_limit',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_media_size_mb',
        ),
        migrations.AddField(
            model_name='plan',
            name='max_upload_mb',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_video_seconds',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='plan',
            name='media_uploads_per_month',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='posting_reminders_per_month',
            field=models.IntegerField(default=30),
        ),
    ]
