# Generated by Django 5.2.3 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_plan_active_platforms_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='will_cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
